export const BASE_SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS memory_items (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    summary TEXT NOT NULL,
    memory_type TEXT NOT NULL,
    memory_scope TEXT NOT NULL DEFAULT 'cross_mission',
    memory_layer TEXT NOT NULL DEFAULT 'working',
    memory_subtype TEXT NOT NULL DEFAULT 'custom.general',
    source TEXT NOT NULL,
    confidence REAL NOT NULL,
    owner TEXT NOT NULL,
    owner_scope TEXT NOT NULL DEFAULT 'private',
    domain TEXT,
    reusable INTEGER NOT NULL,
    supersedes TEXT,
    superseded_by TEXT,
    mission_id TEXT,
    tags TEXT NOT NULL,
    entity_keys TEXT NOT NULL DEFAULT '[]',
    entity_aliases TEXT NOT NULL DEFAULT '[]',
    written_by TEXT NOT NULL DEFAULT 'system',
    retrieval_weight REAL NOT NULL DEFAULT 1,
    promotion_state TEXT NOT NULL DEFAULT 'none',
    times_reused INTEGER NOT NULL DEFAULT 0,
    last_reused_at INTEGER,
    success_rate_hint REAL,
    status TEXT NOT NULL,
    verified_by TEXT,
    evidence_ref TEXT NOT NULL,
    version INTEGER NOT NULL,
    review_due_at INTEGER,
    stale_after_at INTEGER,
    archive_after_at INTEGER,
    expires_at INTEGER,
    archived_at INTEGER,
    last_validated_at INTEGER,
    valid_until INTEGER,
    embedding_status TEXT NOT NULL DEFAULT 'disabled',
    embedding_updated_at INTEGER,
    embedding_model_version TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_memory_type ON memory_items(memory_type)`,
  `CREATE INDEX IF NOT EXISTS idx_memory_domain ON memory_items(domain)`,
  `CREATE INDEX IF NOT EXISTS idx_memory_mission ON memory_items(mission_id)`,
  `CREATE INDEX IF NOT EXISTS idx_memory_status ON memory_items(status)`,
  `CREATE INDEX IF NOT EXISTS idx_memory_updated ON memory_items(updated_at)`,
  `CREATE TABLE IF NOT EXISTS memory_versions (
    id TEXT PRIMARY KEY,
    memory_id TEXT NOT NULL,
    version INTEGER NOT NULL,
    content TEXT NOT NULL,
    summary TEXT NOT NULL,
    source TEXT NOT NULL,
    verified_by TEXT,
    evidence_ref TEXT NOT NULL,
    change_summary TEXT,
    created_at INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_memory_versions_memory ON memory_versions(memory_id)`,
  `CREATE VIRTUAL TABLE IF NOT EXISTS memory_fts USING fts5(
    memory_id UNINDEXED,
    title,
    summary,
    content,
    entity_keys,
    entity_aliases,
    tags
  )`,
  `CREATE TABLE IF NOT EXISTS memory_embeddings (
    memory_id TEXT PRIMARY KEY,
    embedding_provider TEXT,
    embedding_model TEXT,
    embedding_model_version TEXT,
    embedding_doc_hash TEXT,
    embedding_status TEXT NOT NULL,
    embedding_updated_at INTEGER
  )`,
  `CREATE TABLE IF NOT EXISTS memory_promotions (
    id TEXT PRIMARY KEY,
    source_memory_id TEXT NOT NULL,
    promoted_memory_id TEXT,
    target_layer TEXT NOT NULL,
    state TEXT NOT NULL,
    reason TEXT NOT NULL,
    reviewed_by TEXT,
    reviewed_at INTEGER,
    created_at INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_memory_promotions_source ON memory_promotions(source_memory_id, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS memory_contradictions (
    id TEXT PRIMARY KEY,
    left_memory_id TEXT NOT NULL,
    right_memory_id TEXT NOT NULL,
    conflict_kind TEXT NOT NULL,
    resolution_state TEXT NOT NULL,
    chosen_memory_id TEXT,
    resolution_reason TEXT,
    resolved_by TEXT,
    resolved_at INTEGER,
    mission_id TEXT,
    created_at INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_memory_contradictions_left ON memory_contradictions(left_memory_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_memory_contradictions_right ON memory_contradictions(right_memory_id, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS memory_file_mirror (
    memory_id TEXT PRIMARY KEY,
    relative_path TEXT NOT NULL,
    exported_at INTEGER,
    imported_at INTEGER,
    export_hash TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS memory_edges (
    id TEXT PRIMARY KEY,
    from_id TEXT NOT NULL,
    to_id TEXT NOT NULL,
    edge_type TEXT NOT NULL,
    weight REAL NOT NULL DEFAULT 1,
    metadata TEXT NOT NULL,
    created_at INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_memory_edges_from ON memory_edges(from_id)`,
  `CREATE INDEX IF NOT EXISTS idx_memory_edges_to ON memory_edges(to_id)`,
  `CREATE TABLE IF NOT EXISTS missions (
    id TEXT PRIMARY KEY,
    objective TEXT NOT NULL,
    domain TEXT,
    status TEXT NOT NULL,
    planning_hints TEXT NOT NULL,
    preferred_format TEXT,
    verification_required INTEGER NOT NULL,
    latest_outcome_memory_id TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    started_at INTEGER,
    completed_at INTEGER,
    rejected_reason TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS idx_missions_status ON missions(status)`,
  `CREATE TABLE IF NOT EXISTS mission_events (
    id TEXT PRIMARY KEY,
    mission_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    actor TEXT NOT NULL,
    detail TEXT NOT NULL,
    data TEXT NOT NULL,
    created_at INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_mission_events_mission ON mission_events(mission_id, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS verification_runs (
    id TEXT PRIMARY KEY,
    mission_id TEXT NOT NULL,
    status TEXT NOT NULL,
    requested_by TEXT NOT NULL,
    summary TEXT,
    evidence_ref TEXT NOT NULL,
    verification_checks TEXT NOT NULL,
    started_at INTEGER NOT NULL,
    completed_at INTEGER
  )`,
  `CREATE INDEX IF NOT EXISTS idx_verification_runs_mission ON verification_runs(mission_id, started_at DESC)`,
  `CREATE TABLE IF NOT EXISTS verification_artifacts (
    id TEXT PRIMARY KEY,
    mission_id TEXT,
    verification_run_id TEXT,
    memory_id TEXT,
    artifact_type TEXT NOT NULL,
    artifact_ref TEXT NOT NULL,
    artifact_description TEXT,
    source_kind TEXT NOT NULL,
    created_at INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_verification_artifacts_mission ON verification_artifacts(mission_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_verification_artifacts_run ON verification_artifacts(verification_run_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_verification_artifacts_memory ON verification_artifacts(memory_id, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS retrieval_traces (
    id TEXT PRIMARY KEY,
    query TEXT NOT NULL,
    intent TEXT NOT NULL,
    query_profile TEXT NOT NULL DEFAULT 'balanced',
    mission_id TEXT,
    domain TEXT,
    policy_path TEXT NOT NULL,
    retrieval_mode TEXT NOT NULL DEFAULT 'fts_only',
    matched_candidates TEXT NOT NULL,
    why_included TEXT NOT NULL,
    why_excluded TEXT NOT NULL,
    ranking_contribution TEXT NOT NULL,
    final_selected_set TEXT NOT NULL,
    created_at INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS learning_events (
    id TEXT PRIMARY KEY,
    mode TEXT NOT NULL,
    memory_id TEXT,
    mission_id TEXT,
    action TEXT NOT NULL,
    accepted INTEGER NOT NULL,
    reason TEXT NOT NULL,
    payload TEXT NOT NULL,
    created_at INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_learning_events_created ON learning_events(created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS scheduled_missions (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    goal TEXT NOT NULL,
    worker_preference TEXT NOT NULL DEFAULT 'auto',
    cadence_kind TEXT NOT NULL,
    cadence_config TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    paused INTEGER NOT NULL DEFAULT 0,
    run_lock INTEGER NOT NULL DEFAULT 0,
    run_lock_token TEXT,
    run_count INTEGER NOT NULL DEFAULT 0,
    success_count INTEGER NOT NULL DEFAULT 0,
    failure_count INTEGER NOT NULL DEFAULT 0,
    last_status TEXT NOT NULL DEFAULT 'idle',
    last_error TEXT,
    last_run_mission_id TEXT,
    last_run_started_at INTEGER,
    last_run_finished_at INTEGER,
    next_run_at INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_scheduled_missions_next_run ON scheduled_missions(enabled, paused, run_lock, next_run_at ASC)`,
];

export const POST_MIGRATION_SCHEMA_STATEMENTS = [
  `CREATE INDEX IF NOT EXISTS idx_memory_scope ON memory_items(memory_scope)`,
  `CREATE INDEX IF NOT EXISTS idx_memory_layer ON memory_items(memory_layer)`,
  `CREATE INDEX IF NOT EXISTS idx_memory_subtype ON memory_items(memory_subtype)`,
  `CREATE INDEX IF NOT EXISTS idx_memory_reused ON memory_items(times_reused, last_reused_at DESC)`,
];

export const SCHEMA_STATEMENTS = [...BASE_SCHEMA_STATEMENTS, ...POST_MIGRATION_SCHEMA_STATEMENTS];
