import fs from 'fs';
import path from 'path';
import type { VerificationArtifact, VerificationCheck } from '../types.ts';

export interface MailMessage {
  id: string;
  from: string;
  to: string;
  subject: string;
  body: string;
  received_at: string;
}

export interface MailWorkerRunInput {
  mission_id: string;
  task_id: string;
  prompt: string;
  cwd: string;
  mailbox_path?: string | null;
  now?: () => Date;
}

export interface MailWorkerRunResult {
  summary: string;
  status: 'success' | 'needs_retry' | 'failed';
  artifacts: VerificationArtifact[];
  checks: VerificationCheck[];
  raw_output: string;
  invocation: {
    command: string;
    args: string[];
    cwd: string;
    exit_code: number;
    timed_out: boolean;
    started_at: number;
    completed_at: number;
    transport: 'manager_owned';
  };
  process_output: {
    stdout: string;
    stderr: string;
  };
}

type MailIntent = 'draft' | 'inbox_summary' | 'search' | 'send_request';

function extractGoalText(prompt: string): string {
  const goalLine = prompt
    .split('\n')
    .map((line) => line.trim())
    .find((line) => line.toLowerCase().startsWith('goal: '));
  if (goalLine) {
    return goalLine.replace(/^goal:\s*/i, '').trim();
  }
  return prompt;
}

function detectIntent(goalText: string): MailIntent {
  const normalized = goalText.toLowerCase();
  if (/send\s+(an?\s+)?e-?mail|send email|\u0e2a\u0e48\u0e07\u0e40\u0e21\u0e25|\u0e2a\u0e48\u0e07\u0e2d\u0e35\u0e40\u0e21\u0e25/u.test(normalized)) {
    return 'send_request';
  }
  if (/search|find|lookup|\u0e04\u0e49\u0e19|\u0e2b\u0e32/u.test(normalized)) {
    return 'search';
  }
  if (/draft|compose|\u0e23\u0e48\u0e32\u0e07|\u0e40\u0e02\u0e35\u0e22\u0e19/u.test(normalized)) {
    return 'draft';
  }
  return 'inbox_summary';
}

function resolveMailboxPath(input: MailWorkerRunInput): string {
  if (input.mailbox_path && input.mailbox_path.trim().length > 0) {
    return path.resolve(input.mailbox_path);
  }
  return path.resolve(input.cwd, 'artifacts', 'mail', 'inbox.json');
}

function safeParseMailbox(raw: string): MailMessage[] {
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (!Array.isArray(parsed)) {
      return [];
    }
    return parsed
      .filter((item): item is Record<string, unknown> => typeof item === 'object' && item != null)
      .filter((item) =>
        typeof item.id === 'string'
        && typeof item.from === 'string'
        && typeof item.to === 'string'
        && typeof item.subject === 'string'
        && typeof item.body === 'string'
        && typeof item.received_at === 'string')
      .map((item) => ({
        id: item.id as string,
        from: item.from as string,
        to: item.to as string,
        subject: item.subject as string,
        body: item.body as string,
        received_at: item.received_at as string,
      }));
  } catch {
    return [];
  }
}

function loadMailbox(mailboxPath: string): MailMessage[] {
  if (!fs.existsSync(mailboxPath)) {
    return [];
  }
  return safeParseMailbox(fs.readFileSync(mailboxPath, 'utf8'));
}

function extractRecipient(goalText: string): string {
  const emailMatch = goalText.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)?.[0];
  if (emailMatch) {
    return emailMatch.trim();
  }
  const recipientMatches = Array.from(goalText.matchAll(/(?:to|ถึง)\s+([^\s,;]+)/ig));
  const explicit = recipientMatches.at(-1)?.[1];
  return explicit?.trim() || 'owner@example.local';
}

function extractSubject(goalText: string): string {
  const explicit = goalText.match(/subject[:=]?\s*["']?([^"'\n]+)["']?/i)?.[1];
  if (explicit?.trim()) {
    return explicit.trim();
  }
  return 'Draft from best-brain manager';
}

function extractBody(goalText: string): string {
  const bodyMatch = goalText.match(/body[:=]?\s*["']?([^"']+)["']?/i)?.[1];
  if (bodyMatch?.trim()) {
    return bodyMatch.trim();
  }
  return 'This is a draft generated by the local Mail worker. Review before sending.';
}

function summarizeInbox(messages: MailMessage[]): string {
  if (messages.length === 0) {
    return 'Inbox summary: 0 messages found in the local mailbox.';
  }
  const ordered = [...messages].sort((left, right) => right.received_at.localeCompare(left.received_at)).slice(0, 5);
  const lines = ordered.map((message, index) => `${index + 1}. ${message.subject} (from ${message.from})`);
  return `Inbox summary: ${messages.length} total messages.\n${lines.join('\n')}`;
}

function extractSearchQuery(goalText: string): string {
  const normalized = goalText.toLowerCase();
  const marker = normalized.match(/search(?:\s+for)?\s+(.+)$/i)?.[1]
    ?? normalized.match(/\u0e04\u0e49\u0e19(?:\u0e2b\u0e32)?\s+(.+)$/u)?.[1]
    ?? '';
  return marker.trim();
}

export async function runMailWorkerTask(input: MailWorkerRunInput): Promise<MailWorkerRunResult> {
  const nowDate = input.now ?? (() => new Date());
  const startedAt = nowDate().getTime();
  const goalText = extractGoalText(input.prompt);
  const intent = detectIntent(goalText);
  const mailboxPath = resolveMailboxPath(input);
  const mailbox = loadMailbox(mailboxPath);

  if (intent === 'send_request') {
    const completedAt = nowDate().getTime();
    return {
      summary: 'Mail worker blocked send action. Draft-only mode requires explicit operator approval before sending.',
      status: 'needs_retry',
      artifacts: [{
        type: 'note',
        ref: `worker://mail/send-blocked/${input.mission_id}`,
        description: 'Send request was blocked by policy (draft-only mode).',
      }],
      checks: [{
        name: 'mail-send-approved',
        passed: false,
        detail: 'Sending email is blocked in draft-only mode without explicit operator approval.',
      }],
      raw_output: '',
      invocation: {
        command: 'mail_worker',
        args: ['send_request'],
        cwd: input.cwd,
        exit_code: 1,
        timed_out: false,
        started_at: startedAt,
        completed_at: completedAt,
        transport: 'manager_owned',
      },
      process_output: {
        stdout: '',
        stderr: 'Send blocked by policy: draft-only mode.',
      },
    };
  }

  if (intent === 'draft') {
    const draftsDir = path.resolve(input.cwd, 'artifacts', 'mail', 'drafts');
    fs.mkdirSync(draftsDir, { recursive: true });
    const draftPath = path.resolve(draftsDir, `${input.mission_id}_${input.task_id}.json`);
    const draft = {
      id: `draft_${input.mission_id}_${input.task_id}`,
      to: extractRecipient(goalText),
      subject: extractSubject(goalText),
      body: extractBody(goalText),
      created_at: nowDate().toISOString(),
      source: 'mail-worker-draft-only',
    };
    fs.writeFileSync(draftPath, JSON.stringify(draft, null, 2));
    const completedAt = nowDate().getTime();
    return {
      summary: `Mail worker created a local draft for ${draft.to} with subject "${draft.subject}".`,
      status: 'success',
      artifacts: [
        {
          type: 'file',
          ref: draftPath,
          description: 'Draft email JSON artifact.',
        },
        {
          type: 'note',
          ref: `worker://mail/draft/${input.mission_id}`,
          description: `Drafted email to ${draft.to} with subject "${draft.subject}".`,
        },
      ],
      checks: [
        {
          name: 'mail-draft-created',
          passed: true,
          detail: `Draft saved at ${draftPath}.`,
        },
        {
          name: 'mail-send-not-executed',
          passed: true,
          detail: 'No send action was executed (draft-only mode).',
        },
      ],
      raw_output: JSON.stringify(draft),
      invocation: {
        command: 'mail_worker',
        args: ['draft'],
        cwd: input.cwd,
        exit_code: 0,
        timed_out: false,
        started_at: startedAt,
        completed_at: completedAt,
        transport: 'manager_owned',
      },
      process_output: {
        stdout: `Draft saved: ${draftPath}`,
        stderr: '',
      },
    };
  }

  if (intent === 'search') {
    const query = extractSearchQuery(goalText).toLowerCase();
    const matches = query.length === 0
      ? mailbox
      : mailbox.filter((message) =>
        message.subject.toLowerCase().includes(query) || message.body.toLowerCase().includes(query));
    const completedAt = nowDate().getTime();
    const summary = query.length === 0
      ? `Mail worker search ran with empty query and returned ${matches.length} messages.`
      : `Mail worker search for "${query}" returned ${matches.length} messages.`;
    return {
      summary,
      status: 'success',
      artifacts: [{
        type: 'note',
        ref: `worker://mail/search/${input.mission_id}`,
        description: matches.slice(0, 5).map((message) => `${message.subject} (${message.from})`).join(' | ') || 'No matches found.',
      }],
      checks: [{
        name: 'mailbox-search-completed',
        passed: true,
        detail: `Search completed against ${mailbox.length} local mailbox records.`,
      }],
      raw_output: JSON.stringify(matches),
      invocation: {
        command: 'mail_worker',
        args: ['search', query || '<empty>'],
        cwd: input.cwd,
        exit_code: 0,
        timed_out: false,
        started_at: startedAt,
        completed_at: completedAt,
        transport: 'manager_owned',
      },
      process_output: {
        stdout: summary,
        stderr: '',
      },
    };
  }

  const inboxSummary = summarizeInbox(mailbox);
  const completedAt = nowDate().getTime();
  return {
    summary: `Mail worker prepared local inbox summary from ${mailbox.length} messages.`,
    status: 'success',
    artifacts: [{
      type: 'note',
      ref: `worker://mail/inbox-summary/${input.mission_id}`,
      description: inboxSummary,
    }],
    checks: [{
      name: 'mailbox-loaded',
      passed: true,
      detail: `Loaded ${mailbox.length} messages from ${mailboxPath}.`,
    }],
    raw_output: JSON.stringify(mailbox),
    invocation: {
      command: 'mail_worker',
      args: ['inbox_summary'],
      cwd: input.cwd,
      exit_code: 0,
      timed_out: false,
      started_at: startedAt,
      completed_at: completedAt,
      transport: 'manager_owned',
    },
    process_output: {
      stdout: inboxSummary,
      stderr: '',
    },
  };
}
