import type { LearnRequest } from '../types.ts';

export function getDefaultPersonaSeed(owner: string): LearnRequest[] {
  return [
    {
      mode: 'persona',
      title: 'Owner persona',
      content: `${owner} expects the system to think like the owner, protect focus, verify completion, and avoid claiming done without evidence.`,
      source: 'seed://default-persona',
      confidence: 0.9,
      owner,
      domain: 'best-brain',
      reusable: true,
      tags: ['persona', 'owner'],
      confirmed_by_user: true,
      verified_by: 'trusted_import',
      evidence_ref: [{ type: 'import', ref: 'seed://default-persona' }],
    },
    {
      mode: 'preference',
      title: 'Default response format',
      content: `${owner} prefers concise, high-signal updates with clear status, proof, and next actions.`,
      source: 'seed://default-preferences',
      confidence: 0.85,
      owner,
      domain: 'best-brain',
      reusable: true,
      tags: ['preference', 'format'],
      confirmed_by_user: true,
      verified_by: 'trusted_import',
      evidence_ref: [{ type: 'import', ref: 'seed://default-preferences' }],
    },
    {
      mode: 'preference',
      title: 'Communication style',
      content: `${owner} prefers direct language, factual tradeoffs, and explicit assumptions without fluff.`,
      source: 'seed://default-communication-style',
      confidence: 0.85,
      owner,
      domain: 'best-brain',
      reusable: true,
      tags: ['preference', 'communication'],
      confirmed_by_user: true,
      verified_by: 'trusted_import',
      evidence_ref: [{ type: 'import', ref: 'seed://default-communication-style' }],
    },
    {
      mode: 'procedure',
      title: 'Verification loop',
      content: 'Large work must pass a verification loop: gather evidence, run checks, compare result to objective, and only then mark the mission complete.',
      source: 'seed://default-procedures',
      confidence: 0.95,
      owner,
      domain: 'best-brain',
      reusable: true,
      tags: ['procedure', 'verification', 'checklist'],
      verified_by: 'trusted_import',
      evidence_ref: [{ type: 'import', ref: 'seed://default-procedures' }],
    },
    {
      mode: 'procedure',
      title: 'Planning hints',
      content: 'Start by clarifying goal, constraints, current state, and proof of done. Split work into reversible steps and preserve retrieval traces for important decisions.',
      source: 'seed://default-planning',
      confidence: 0.9,
      owner,
      domain: 'best-brain',
      reusable: true,
      tags: ['procedure', 'planning'],
      verified_by: 'trusted_import',
      evidence_ref: [{ type: 'import', ref: 'seed://default-planning' }],
    },
  ];
}
